"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TypoWeights = exports.TypoSizes = exports.TypoTypes = void 0;
var TypoTypes;
(function (TypoTypes) {
    TypoTypes["default"] = "default";
    TypoTypes["disabled"] = "disabled";
    TypoTypes["error"] = "error";
    TypoTypes["invert"] = "invert";
    TypoTypes["link"] = "link";
    TypoTypes["title"] = "title";
    TypoTypes["sub"] = "sub";
    TypoTypes["subTitle"] = "sub-title";
    TypoTypes["formLabel"] = "form-label";
    TypoTypes["success"] = "success";
    TypoTypes["warning"] = "warning";
    TypoTypes["strikethrough"] = "strikethrough";
    TypoTypes["inherit"] = "inherit";
    TypoTypes["primary"] = "primary";
    TypoTypes["secondary"] = "secondary";
    TypoTypes["price"] = "price";
    TypoTypes["darkTitle"] = "dark-title";
    TypoTypes["hint"] = "hint";
})(TypoTypes = exports.TypoTypes || (exports.TypoTypes = {}));
var TypoSizes;
(function (TypoSizes) {
    TypoSizes["bigtitle3"] = "bigtitle3";
    TypoSizes["title1"] = "title1";
    TypoSizes["title2"] = "title2";
    TypoSizes["title3"] = "title3";
    TypoSizes["title4"] = "title4";
    TypoSizes["subtitle1"] = "subtitle1";
    TypoSizes["subtitle2"] = "subtitle2";
    TypoSizes["subtitle3"] = "subtitle3";
    TypoSizes["body1"] = "body1";
    TypoSizes["body2"] = "body2";
    TypoSizes["link"] = "link";
    TypoSizes["caption"] = "caption";
    TypoSizes["inherit"] = "inherit";
    TypoSizes["tiny"] = "tiny";
})(TypoSizes = exports.TypoSizes || (exports.TypoSizes = {}));
var TypoWeights;
(function (TypoWeights) {
    TypoWeights["bold"] = "bold";
    TypoWeights["medium"] = "medium";
    TypoWeights["regular"] = "regular";
    TypoWeights["light"] = "light";
    TypoWeights["inherit"] = "inherit";
    TypoWeights["link"] = "link";
})(TypoWeights = exports.TypoWeights || (exports.TypoWeights = {}));
exports.default = TypoTypes;
//# sourceMappingURL=TypoTypes.jsx.map